import textwrap
name = input('Введите ФИО:')
date = input('Введите дату:')
experiment = input('Введите название эксперимента:')
result = input('Введите вывод:')
word = len(name)
space = ' '*(29 - word)
word_date = len(date)
space_date = ' '*(29 - word_date)
word_experiment = len(experiment)
space_experiment = ' '*(29 - word_experiment)
wrapper = textwrap.TextWrapper(width=50)
lines = wrapper.wrap(result)
with open('journal.txt', 'w', encoding='utf-8') as journal:
    journal.write('+--------------------------------------------------+\n')
    journal.write('| Электронный лабораторный журнал                  |\n')
    journal.write('+--------------------------------------------------+\n')
    journal.write(f'| ФИО исследователя : {name}{space}|\n')
    journal.write(f'| Дата              : {date}{space_date}|\n')
    journal.write(f'| Эксперимент       : {experiment}{space_experiment}|\n')
    journal.write('+--------------------------------------------------+\n')
    journal.write('| Вывод:                                           |\n')
    for line in lines:
        word_line = len(line)
        space_line = ' '*(50 - word_line)
        journal.write(f'|{line}{space_line}|\n')
    journal.write('+--------------------------------------------------+')